project_id = "rjkgxkruvfjutgejrjbq"

[functions.request-password-reset]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.send-password-changed]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
